openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /greeting:
    get:
      summary: A resource for generating greetings
      operationId: getGreeting
      parameters:
      - name: name
        in: query
        description: the input string name
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
  /contacts:
    get:
      summary: A resource for fetching contacts from salesforce
      operationId: getContacts
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactsOutput'
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
    post:
      summary: A resource for transforming contacts
      operationId: postContacts
      requestBody:
        description: the input contacts
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactsInput'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactsOutput'
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
components:
  schemas:
    RecordsItem:
      required:
      - Email
      - FirstName
      - Id
      - LastName
      - Phone
      - attributes
      type: object
      properties:
        attributes:
          $ref: '#/components/schemas/Attributes'
        Id:
          type: string
        FirstName:
          type: string
        LastName:
          type: string
        Email:
          nullable: true
          oneOf:
          - {}
          - type: string
        Phone:
          nullable: true
          oneOf:
          - {}
          - type: string
    ContactsOutput:
      required:
      - contacts
      - numberOfContacts
      type: object
      properties:
        numberOfContacts:
          type: integer
          format: int64
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/ContactsItem'
    Attributes:
      required:
      - type
      - url
      type: object
      properties:
        type:
          type: string
        url:
          type: string
    ContactsItem:
      required:
      - email
      - fullName
      - id
      - phoneNumber
      type: object
      properties:
        fullName:
          type: string
        phoneNumber:
          nullable: true
          oneOf:
          - {}
          - type: string
        email:
          nullable: true
          oneOf:
          - {}
          - type: string
        id:
          type: string
    ContactsInput:
      required:
      - done
      - records
      - totalSize
      type: object
      properties:
        totalSize:
          type: integer
          format: int64
        done:
          type: boolean
        records:
          type: array
          items:
            $ref: '#/components/schemas/RecordsItem'
